= Cookie Policy
include::ROOT:partial$include.adoc[]

### Introduction

This website ("**Site**") is owned and controlled by the Authors of the Reactive Principles ("**Reactive Principles**", "**we**", "**us**" or "**our**") .

Our Site uses technologies that enhance user friendliness and engagement, to keep the website operating as smoothly as possible and to provide web services and functionalities for each visitor. Examples of these technologies are cookies, pixel tags, local storage and scripts (hereinafter collectively referred to as "**cookies**").

Cookies may be either "persistent" cookies or "session" cookies. A persistent cookie consists of a text file sent by a web server to a web browser, which will be stored by the browser and will remain valid until its set expiry date (unless deleted by the visitor before the expiry date). A session cookie, on the other hand, will expire at the end of the visitor session, when the web browser is closed.

This cookie policy describes the options available to you how to manage your cookies, which cookies we use and for what purposes we use them.

How To Manage Cookies
---------------------

If you do not want our websites to store cookies on your computer or mobile device, you can change your browser settings so that you receive a warning before certain cookies are stored. You can also adjust your settings so that your browser refuses most of our cookies or only certain cookies. You can also withdraw your consent to cookies by deleting the cookies that have already been stored.

Please be aware that if you do not want to accept any cookies, we cannot guarantee that our website will function properly. It may be that several functions will be unavailable to you or that you will even be unable to view certain parts of the website

Please note that you will have to change your settings for each browser and device you use. The procedures for changing your settings and cookies differ from browser to browser if necessary, use the help function on your browser or click on one of the links below to go directly to the use manual for your browser:

*   [Internet Explorer](https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies)
*   [Mozilla Firefox](https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored)
*   [Google Chrome](https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en)
*   [Safari](https://support.apple.com/kb/ph21411?locale=en_US)
*   [Opera](https://www.opera.com/help/tutorials/security/privacy/)
*   [Adobe (plug-in for flash cookies)](https://www.adobe.com/privacy/cookies.html)

There are also software products available that can manage cookies for you.

To find out more about cookies, including how to see what cookies have been set and how to manage or delete them, visit [All About Cookies.org](http://www.allaboutcookies.org/).

Because we respect your right to privacy, you can choose not to allow some types of cookies. Below is a list of the cookies that get set on the reactivemanifesto.org domain. Blocking some types of cookies may impact your experience of the site and the services we are able to offer.

Cookie Settings

* * *

Cookie Listing
--------------

<div id="ot-sdk-cookie-policy"></div>

Policy Update
-------------

We may change this cookie policy from time to time. If a fundamental change is involved that requires us to inform you about this, or if the change is in any other manner relevant to you, we will ensure that information is provided to you well in advance of the change actually taking effect.


